theme: jekyll-theme-minimal
logo: /assets/img/logo.png
title: Updated Ecological Map of Do√±ana National Park (V1, 2026)
description: With attention to ponds, marsh, toponyms and vernaculars.
links:
  - label: "Google Scholar"
    url: "https://scholar.google.com/citations?user=JQzRGw4AAAAJ&hl=es"
  - label: "Repositorio de datos"
    url: "https://scholar.google.com/citations?user=JQzRGw4AAAAJ&hl=es"
  - label: "Contacto"
    url: "mailto:m.defelipe.t@gmail.com"
