theme: jekyll-theme-minimal
title: Mapa Ecológico Actualizado del Parque Nacional de Doñana
logo: /assets/img/logo.png
description: Información cartográfica y recursos asociados al mapa actualizado del Parque Nacional de Doñana (Miguel de Felipe, 2026).
