theme: jekyll-theme-minimal
title: Mapa Ecológico Actualizado del Parque Nacional de Doñana
logo: /assets/img/logo2.png
description: Información cartográfica y recursos asociados al mapa actualizado del Parque Nacional de Doñana.  Cita recomendada: M. de Felipe (2026). Mapa del Parque Nacional de Doñana (v1.0). Zenodo. DOI: [DOI]
