theme: jekyll-theme-minimal
title: "Ecological Map of Doñana National Park (V1, 2026)"
description: "With special attention to its ponds, marsh, toponyms and vernaculars."

links:
  - label: "Descarga de datos"
    url: "https://zenodo.org/records/13960897"
  - label: "Google Scholar"
    url: "https://scholar.google.com/citations?user=JQzRGw4AAAAJ&hl=es"
  - label: "Researchgate"
    url: "https://www.researchgate.net/profile/Miguel-De-Felipe?ev=prf_overview"
  - label: "Instagram"
    url: "https://www.instagram.com/migueldefelipe/"
  - label: "Contacto"
    url: "mailto:m.defelipe.t@gmail.com"

citation_label: "Cita recomendada:"
citation_text: "M. de Felipe (2026). Mapa del Parque Nacional de Doñana (v1.0). Zenodo."
citation_doi_label: "DOI: [DOI]"
citation_doi_url: "https://doi.org/[DOI]"
